wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
c_1:
  desc: null
  value: 1.6863120996302534
c_2:
  desc: null
  value: 1.744586279837725
epochs:
  desc: null
  value: 348
learning_rate:
  desc: null
  value: 0.0005836363718051791
num_hidden_layers:
  desc: null
  value: 2
num_particles:
  desc: null
  value: 50
num_per_layer:
  desc: null
  value: 12
v_max:
  desc: null
  value: 0.11568394815073256
