wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
c_1:
  desc: null
  value: 2.3438270328609083
c_2:
  desc: null
  value: 2.13868046610293
epochs:
  desc: null
  value: 484
learning_rate:
  desc: null
  value: 0.0017818194354974623
num_hidden_layers:
  desc: null
  value: 2
num_particles:
  desc: null
  value: 25
num_per_layer:
  desc: null
  value: 20
v_max:
  desc: null
  value: 0.09597790697529421
