wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/../../../../../../usr/local/bin/wandb
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
c_1:
  desc: null
  value: 1.3458164761517226
c_2:
  desc: null
  value: 1.9258204152518466
epochs:
  desc: null
  value: 346
learning_rate:
  desc: null
  value: 0.0012894216355039162
num_hidden_layers:
  desc: null
  value: 2
num_particles:
  desc: null
  value: 84
num_per_layer:
  desc: null
  value: 5
v_max:
  desc: null
  value: 0.10416995135052075
