wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
c_1:
  desc: null
  value: 1.4726012132477682
c_2:
  desc: null
  value: 1.4076765385600674
epochs:
  desc: null
  value: 310
learning_rate:
  desc: null
  value: 0.0017087492114163428
num_hidden_layers:
  desc: null
  value: 2
num_particles:
  desc: null
  value: 41
num_per_layer:
  desc: null
  value: 9
v_max:
  desc: null
  value: 0.1431640328010195
