wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
c_1:
  desc: null
  value: 1.3746882218571346
c_2:
  desc: null
  value: 2.502860665091401
epochs:
  desc: null
  value: 434
learning_rate:
  desc: null
  value: 0.0015292785592793186
num_hidden_layers:
  desc: null
  value: 2
num_particles:
  desc: null
  value: 29
num_per_layer:
  desc: null
  value: 20
v_max:
  desc: null
  value: 0.15926279007356897
