wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
c_1:
  desc: null
  value: 1.8542048578261794
c_2:
  desc: null
  value: 2.2226882459409767
epochs:
  desc: null
  value: 194
learning_rate:
  desc: null
  value: 0.0013418145226356483
num_hidden_layers:
  desc: null
  value: 2
num_particles:
  desc: null
  value: 28
num_per_layer:
  desc: null
  value: 18
v_max:
  desc: null
  value: 0.14204293666107
