wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.4
batch_size:
  desc: null
  value: 100
channels_one:
  desc: null
  value: 16
channels_two:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
